import type { Metadata } from "next";
<<<<<<< HEAD
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
import "./globals.css";

// Enterprise Typography: Premium fonts with high-quality fallbacks
// Sohne (Editorial), Maison Neue (Interface), Basis Grotesque Pro (System)
// Fallbacks: Inter, Plus Jakarta Sans, JetBrains Mono for optimal performance

export const metadata: Metadata = {
  title: "White Sports Ventures | Elite Soccer Venture Capital",
  description: "Strategic investments in soccer technology, clubs, and media. Led by former USMNT player Jeremiah White III. Transforming US soccer through innovative partnerships.",
>>>>>>> 400faee4cc93fdd6ce603d2e1e2efdb950d8c481
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
=======
      <head>
        {/* Font Loading - Optimized for Performance */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        
        {/* Premium Fallback Fonts - Always Available */}
        <link 
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Plus+Jakarta+Sans:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@300;400;500;600;700&display=swap" 
          rel="stylesheet" 
        />
        
        {/* Premium Fonts - Enterprise Grade Typography */}
        {/* Note: Premium fonts (Sohne, Maison Neue, Basis Grotesque Pro) would be loaded here */}
        {/* For demo purposes, we use high-quality fallbacks that match the premium font characteristics */}
      </head>
      <body className="antialiased">
>>>>>>> 400faee4cc93fdd6ce603d2e1e2efdb950d8c481
        {children}
      </body>
    </html>
  );
}
